# Generated by Django 5.0.6 on 2024-05-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuitem_specification_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuimages',
            old_name='menuItem',
            new_name='menuIt',
        ),
    ]
