# Generated by Django 5.0.6 on 2024-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recent',
            field=models.BooleanField(default=False),
        ),
    ]
