# Generated by Django 5.0.6 on 2024-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review_delete_menureview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '✮☆☆☆☆'), (2, '✮✮☆☆☆'), (3, '✮✮✮☆☆'), (4, '✮✮✮✮☆'), (5, '✮✮✮✮✮')], default=None),
        ),
    ]
